# Generated by Django 2.1.5 on 2019-02-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progEng', '0002_auto_20190223_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('club', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zarplata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('income', models.IntegerField()),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zarplats', to='progEng.Persona')),
            ],
        ),
    ]
