# Generated by Django 2.1.5 on 2019-03-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progEng', '0003_persona_zarplata'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='vid_s',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
